### ISSUE TITLE
Calibração

### ISSUE THREAD

**Issue by RebeccaGH1** [Gabriel-Assuncao/COVIDIBGE#1]
Bom dia, Gabriel! Eu sei que o pacote que vocês criaram já possibilita o acesso aos dados incorporando o design da amostra mestra, mas estou tentando recriar isso (para fins de estudo) e gostaria de saber se, neste caso específico, como os dados são mensais, ainda é necessário fazer calibração? Ou basta considerar os pesos, estratos e clusters?
Muito obrigada, estou realmente impressionada com esse pacote e com os vários documentos e vidéo-aulas seus, explicando estes dados.

**Comment by Gabriel-Assuncao** [comment]
Prezada @RebeccaGH1, boa tarde.
Ficamos gratos em saber que o pacote e os materiais disponibilizados têm sido de utilidade para os usuários.
Sobre a questão da calibração, é uma etapa fundamental, visto que os pesos básicos que envolvem as UPAs e os estratos consideram os totais baseados em quantitativos de domicílios, porém nossos resultados em geral são em nível populacional, então a etapa de calibração serve para que os pesos sejam ajustados e forneçam valores baseados nos totais populacionais da projeção de referência.
Espero que as informações acima tenham sido suficientes, irei fechar esta _issue_ e qualquer dúvida solicito por gentileza que entre em contato através do canal de atendimento pacotesipd@ibge.gov.br.
